version: '3.9'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules  # Avoid overwriting container's node_modules
    env_file:
      - .env.local
    working_dir: /app
    command: npm run dev 